# Site settings
title: A basdasd
description: A bloads
baseurl: "/" 
url: "https://aleyg.github.io" 


# User settings
username: Pagina
user_description: aaaa
user_title: Software Developer
email: azxcn@gmail.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

plugins:
  - "jekyll-github-metadata"

exclude: ['package.json', 'src' , 'node_modules']
